snapshot-labs/sx-api

src/config.json
src/schema.gql
src/writer.ts

Also now we can index strategies params

Update to latest deployment

---

src/config.json

https://github.com/snapshot-labs/sx-core/blob/35e5401c1c5640008812e355d4fb2ee58405d5a4/deployments/goerli4.json

feat: update to latest deployment

---

package.json
src/schema.gql
yarn.lock

Test with:
https://github.com/snapshot-labs/checkpoint/pull/146
Sample query:
```gql
{
proposals(where: {space: "0x00847ae39833c61fe964bfac857ad8c5fa261ec4c716c61b8f28c4ae61fe376b"}) {
id
title
author {
id
vote_count
}
space {
id
name
authenticators
}
}
}
```

feat: enable nested queries

---

.eslintrc
.prettierrc
package.json
yarn.lock

chore: use shared eslint and prettier configs

---

package.json
src/abis/space.json
src/abis/spaceFactory.json
src/config.json
src/index.ts
src/schema.gql
src/utils.ts
src/writer.ts
yarn.lock

- Use ABIs to parse events.
- Use 1-n subentities.
```gql
{
spaces {
id
name
proposal_count
tx
strategies
strategies_params
proposals {
id
proposal_id
title
quorum
max_end
min_end
}
}
votes {
id
voter {
id
}
space {
id
}
}
}
```

feat: upgrade to@snapshot-labs/checkpoint@0.1.0-beta.14

---

package.json
yarn.lock

Fixes issue with parsing vote_created event.

feat: upgrade to@snapshot-labs/checkpoint@0.1.0-beta.15

---

src/schema.gql
src/writer.ts

This PR will index new properties of the space from metadata.
- Create your own space, or start indexing from 86644
- Run query:
```gql
{
spaces(orderBy: created, orderDirection: desc) {
name
about
external_url
github
twitter
discord
wallet
}
}
```

feat: index space properties

---

src/schema.gql

Somehow ended up in wrong entity.

fix: move executed to proposal

---

src/schema.gql
src/writer.ts

Added for compatibility with sx-subgraph

feat: add strategies_metadata

---

package.json
yarn.lock

Now it should be able to index all data properly, indexing wasn't working properly because checkpoints were not sorted by block number.

chore: upgrade to checkpoint@0.1.0-beta.17

---

.github/workflows/build-test.yml
package.json
src/abis/encoders.json
src/abis/executionStrategy.json
src/abis/l1/SimpleQuorumExecutionStrategy.json
src/abis/space.json
src/abis/spaceFactory.json
src/config.json
src/index.ts
src/ipfs.ts
src/schema.gql
src/utils.ts
src/writer.ts
yarn.lock

Depends on https://github.com/checkpoint-labs/checkpoint/pull/245

feat: add sx-starknet v1 support

---

src/config.json
yarn.lock

Also updated yarn.lock as it was outdated.

feat: enable optimistic indexing

---

src/utils.ts
src/writer.ts

I left localhost URL in code so it would fail to properly read execution details. Also path for execution hash was wrong.

fix: index execution data

---

.github/workflows/build-test.yml
.gitignore
package.json
src/config.json
src/index.ts
src/ipfs.ts
src/schema.gql
src/utils.ts
src/writer.ts
yarn.lock

Depends on: https://github.com/checkpoint-labs/checkpoint/pull/253
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/252

refactor: use Checkpoint ORM

---

src/ipfs.ts
src/schema.gql

Depends on: https://github.com/snapshot-labs/sx-api/pull/186

feat: add payload to strategies parsed metadata

---

src/schema.gql
src/writer.ts

Will be used to display on Votes page.

feat: index vote tx

---

package.json
yarn.lock

This unifies OrderBy types with thegraph so we can use it in unified way.

chore: bump @snapshot-labs/checkpoint

---

src/abis/space.json
src/abis/spaceFactory.json
src/config.json
src/index.ts

Depends on: https://github.com/snapshot-labs/sx.js/pull/227

chore: update to post-audit deployment

---

src/schema.gql

validation_strategy_params might not fit in String type (256 chars)

fix: use Text type for validation_strategy_params field

---

src/ipfs.ts
src/schema.gql

Encoding as JSON similar to execution.

feat: index multiple delegations

---

package.json
src/overrrides.ts
src/utils.ts
src/writer.ts
yarn.lock

Works with https://github.com/snapshot-labs/mana/pull/125
1. Run https://github.com/snapshot-labs/mana/pull/125 using test plan.
2. Update `manaRpcUrl` to match your local mana.
3. Let it sync.
4. When new proposal is found check Mana to proceed.

feat: add herodotus support
